### ISSUE TITLE
Bug: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#72]
this is the traceback I get when I run the migration. It could be related to python version but I'm using 3.10

```
Traceback (most recent call last):
  File "/Users/arun/Documents/DDP_backend/manage.py", line 22, in <module>
    main()
  File "/Users/arun/Documents/DDP_backend/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/arun/Documents/DDP_backend/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/arun/.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/arun/Documents/DDP_backend/ddpui/urls.py", line 5, in <module>
    from ddpui.api.client.airbyte_api import airbyteapi
  File "/Users/arun/Documents/DDP_backend/ddpui/api/client/airbyte_api.py", line 21, in <module>
    from ddpui.ddpprefect.prefect_service import run_airbyte_connection_sync
  File "/Users/arun/Documents/DDP_backend/ddpui/ddpprefect/prefect_service.py", line 19, in <module>
    def get_airbyte_server_block_id(blockname) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by fatchat** [comment]
Looks like your venv is 3.9

**Comment by siddhant3030** [comment]
done
